server:
  port: 8091
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.81.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123
    
#配置springmvc的视图解析器
  mvc:         #引入mvn配置
    view:
      prefix: /WEB-INF/views/   # /默认代表根目录 src/main/webapp
      suffix: .jsp#SpringBoot整合mybatis-plus
mybatis-plus:
#定义别名包 当程序自动映射时自动拼接
  type-aliases-package: com.jt.pojo
  #必须编辑映射文件 在映射文件中写sql
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
#引入logger日志
logging:  level:    #扫描的包路径
    com.jt.mapper: debug
  
  